### ISSUE TITLE
Exception raised by ATArest focus get/set

### ISSUE THREAD

**Issue by wfarah** [SETIatHCRO/ATA-Utils#16]
@tkoumrian I think this happens when the focus of certain antennas is set to a large frequency, say 10.5GHz, and then I try to set it back down to 1.5GHz.

Exception:

```
2021-06-17 16:42:13 ERROR ATATools.ata_control: /antennas/1a,1f,1k,5c,1h,4j,3d,4g,2h,2a,1c,2b/focus got error: Command failed - Command returned: ''
Traceback (most recent call last):
  File "/home/obsuser/miniconda3/envs/ATAobs/lib/python3.8/site-packages/ATATools/ata_rest.py", line 71, in _do_op
    raise ATARestException(json[cls.RETURN_MSG_KEY])
ATATools.ata_rest.ATARestException: Command failed - Command returned: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "observe_j0332+5434.py", line 50, in <module>
    main()
  File "observe_j0332+5434.py", line 33, in main
    ata_control.set_freq(freqs, ant_list)
  File "/home/obsuser/miniconda3/envs/ATAobs/lib/python3.8/site-packages/ATATools/ata_control.py", line 833, in set_freq
    set_freq_focus(freq, antlist)
  File "/home/obsuser/miniconda3/envs/ATAobs/lib/python3.8/site-packages/ATATools/ata_control.py", line 777, in set_freq_focus
    ATARest.put(endpoint, data={'value': freq})
  File "/home/obsuser/miniconda3/envs/ATAobs/lib/python3.8/site-packages/ATATools/ata_rest.py", line 109, in put
    return cls._do_op(cls._OP_PUT, endpoint, **kwargs)
  File "/home/obsuser/miniconda3/envs/ATAobs/lib/python3.8/site-packages/ATATools/ata_rest.py", line 78, in _do_op
    raise ATARestException(str(e))
ATATools.ata_rest.ATARestException: Command failed - Command returned: ''
```

Should be easy to test on any of the other antennas

**Comment by tkoumrian** [comment]
I think this may have been some kind of stumble over an antenna that hasn't had it's focus calibrated since the rimbox was last booted.  I found 1k wasn't "calibrated", and after I forced calibration, the group focus worked (took a few minutes, probably the code that attempts to auto cal may need up to 5 minutes for the information to trickle down).  Clearly this isn't ideal, and needs improvement.

A simple workaround is to remember to force calibrate all antennas with working focus drives after a maintenance reboot,
