### ISSUE TITLE
ata_control.make_and_track_tle() does not work

### ISSUE THREAD

**Issue by daniestevez** [SETIatHCRO/ATA-Utils#5]
I'm testing the REST version of ATATools and it seems that TLE tracking isn't working. With a TLE I have in my home dir, I get

```
>>> ac.make_and_track_tle('44453.tle', ['1a'])
/ephemeris got error: Command failed - ephemeris generation failed - The source, /home/obs/ephemeris/44453, was not found or no tracks generated.
Traceback (most recent call last):
  File "/home/destevez/ATA-Utils/pythonLibs/ATATools/ata_rest.py", line 71, in _do_op
    raise ATARestException(json[cls.RETURN_MSG_KEY])
ATATools.ata_rest.ATARestException: Command failed - ephemeris generation failed - The source, /home/obs/ephemeris/44453, was not found or no tracks generated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/destevez/ATA-Utils/pythonLibs/ATATools/ata_control.py", line 329, in make_and_track_tle
    retval = ATARest.post(endpoint, json={'tle': data})
  File "/home/destevez/ATA-Utils/pythonLibs/ATATools/ata_rest.py", line 124, in post
    return cls._do_op(cls._OP_POST, endpoint, **kwargs)
  File "/home/destevez/ATA-Utils/pythonLibs/ATATools/ata_rest.py", line 78, in _do_op
    raise ATARestException(str(e))
ATATools.ata_rest.ATARestException: Command failed - ephemeris generation failed - The source, /home/obs/ephemeris/44453, was not found or no tracks generated.
```

TLE tracking isn't working either with the pre-REST version, but the error is different:

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-9020ec345402> in <module>
----> 1 ac.make_and_track_tle('/home/destevez/44453.tle', ['1a'])

/usr/local/lib/python3.8/dist-packages/ATATools/ata_control.py in make_and_track_tle(tle, antstr)
    318     tle_basename = os.path.basename(tle)
    319 
--> 320     result,errormsg = ata_remote.callObs(['ataephem',
    321         '--tle', '${HOME}/tle/%s' %tle_basename])
    322     logger.info(result)

/usr/local/lib/python3.8/dist-packages/ATATools/ata_remote.py in callObs(myargs)
    161         str_out,str_err = callProg(myargs);
    162     else:
--> 163         str_out,str_err = callProg( ['ssh', OBS_USER +'@' + OBS_HOST ] + myargs )
    164 
    165     return str_out,str_err

/usr/local/lib/python3.8/dist-packages/ATATools/ata_remote.py in callProg(myargs)
     84         logger = logger_defaults.getModuleLogger(__name__)
     85         logger.warning("process '%s' returned error\n %s" % (myargs,str_err))
---> 86         raise RuntimeError("process %s failed" % myargs)
     87 
     88     return str_out,str_err

RuntimeError: process ['ssh', 'obs@control', 'ataephem', '--tle', '${HOME}/tle/44453.tle'] failed
```

Running directly `ataephem` on `control` gives

```
obs@control:~ 01:40:04 > ataephem --tle tle/44453.tle
some unhandled exception - PredictServer not ready/initialized
Problem with object look up (e.g. solar sys, satellite).
PredictServer not ready/initialized
The source, tle/44453, was not found or no tracks generated.
```

So perhaps the problem doesn't have anything to do with ATATools but with the PredictServer at `control`?

**Comment by tkoumrian** [comment]
Hi Daniel,

PredictServer was definitely not working correctly when I checked just now.  I’ve restarted it and command line utilities are working again, so please retry the REST-based calls and see if there is still an error.

**Comment by daniestevez** [comment]
I confirm that this is working now. Thanks!
